
services:
  db-postgres:
    container_name: db-postgres
    image: postgres:17
    ports:
      - "5432:5432"
#    env_file:
#      - path: backend/.env
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123456
      - POSTGRES_DB=user
      - POSTGRES_HOST=db-postgres
      - POSTGRES_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - vlru-app
    restart: always

  backend:
    container_name: backend-nest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - path: backend/.env
    depends_on:
      db-postgres:
        condition: service_healthy
    networks:
      - vlru-app

volumes:
  postgres_data:

networks:
  vlru-app:
    driver: bridge
    name: app-vlru-net