import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1761625177404 implements MigrationInterface {
    name = 'InitialSchema1761625177404'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "blackouts" DROP CONSTRAINT "fk_blackouts_initiators"`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" DROP CONSTRAINT "blackouts_buildings_blackout_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" DROP CONSTRAINT "blackouts_buildings_blackout_id_fkey1"`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" DROP CONSTRAINT "blackouts_buildings_blackout_id_fkey2"`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" DROP CONSTRAINT "blackouts_buildings_blackout_id_fkey3"`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" DROP CONSTRAINT "blackouts_buildings_blackout_id_fkey4"`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" DROP CONSTRAINT "blackouts_buildings_building_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "buildings_big_folk_district_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "buildings_city_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "buildings_district_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "buildings_folk_district_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "buildings_street_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "streets" DROP CONSTRAINT "streets_city_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "streets" DROP CONSTRAINT "streets_city_id_fkey1"`);
        await queryRunner.query(`ALTER TABLE "streets" DROP CONSTRAINT "streets_city_id_fkey2"`);
        await queryRunner.query(`COMMENT ON TABLE "districts" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "folk_districts" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "big_folk_districts" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "blackouts" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "blackouts_buildings" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "buildings" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "cities" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "streets" IS NULL`);
        await queryRunner.query(`CREATE TABLE "complaints" ("id" BIGSERIAL NOT NULL, "building_id" character varying(50) NOT NULL, "blackout_type" character varying(50) NOT NULL, CONSTRAINT "PK_4b7566a2a489c2cc7c12ed076ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`COMMENT ON COLUMN "districts"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "districts"."name" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "folk_districts"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "folk_districts"."name" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "big_folk_districts"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "big_folk_districts"."name" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."start_date" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."end_date" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."predicted_end_date" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."description" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."type" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."source" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts_buildings"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts_buildings"."blackout_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts_buildings"."building_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."street_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."number" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."district_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."is_fake" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."folk_district_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."big_folk_district_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."type" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."city_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."latitude" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."longitude" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cities"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "cities"."name" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "streets"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "streets"."name" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "streets"."city_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "blackouts" ADD CONSTRAINT "FK_20b5ca68f7c7e1097d09c4d52d9" FOREIGN KEY ("initiator_id") REFERENCES "initiators"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" ADD CONSTRAINT "FK_eafa2981ecee8173ab0c7d3f2fd" FOREIGN KEY ("blackout_id") REFERENCES "blackouts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" ADD CONSTRAINT "FK_564bf99933d499afec358b04d88" FOREIGN KEY ("building_id") REFERENCES "buildings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_b23c5f23f51b0e6fd841c8814d4" FOREIGN KEY ("building_id") REFERENCES "buildings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "FK_387c70b151e43add8725368fa3a" FOREIGN KEY ("street_id") REFERENCES "streets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "FK_55fbdd3c40c3fe3dce2ea2094a8" FOREIGN KEY ("district_id") REFERENCES "districts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "FK_48f3f7b8fbbf1ced717d08393ed" FOREIGN KEY ("folk_district_id") REFERENCES "folk_districts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "FK_6544215293ca0bfca5a865a67b3" FOREIGN KEY ("big_folk_district_id") REFERENCES "big_folk_districts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "FK_5b19013b6dde5e639807567bc78" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "streets" ADD CONSTRAINT "FK_fe858303102d63248f4c6505452" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "streets" DROP CONSTRAINT "FK_fe858303102d63248f4c6505452"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "FK_5b19013b6dde5e639807567bc78"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "FK_6544215293ca0bfca5a865a67b3"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "FK_48f3f7b8fbbf1ced717d08393ed"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "FK_55fbdd3c40c3fe3dce2ea2094a8"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "FK_387c70b151e43add8725368fa3a"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_b23c5f23f51b0e6fd841c8814d4"`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" DROP CONSTRAINT "FK_564bf99933d499afec358b04d88"`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" DROP CONSTRAINT "FK_eafa2981ecee8173ab0c7d3f2fd"`);
        await queryRunner.query(`ALTER TABLE "blackouts" DROP CONSTRAINT "FK_20b5ca68f7c7e1097d09c4d52d9"`);
        await queryRunner.query(`COMMENT ON COLUMN "streets"."city_id" IS 'ссылка на город'`);
        await queryRunner.query(`COMMENT ON COLUMN "streets"."name" IS 'название улицы'`);
        await queryRunner.query(`COMMENT ON COLUMN "streets"."id" IS 'уникальный идентификатор'`);
        await queryRunner.query(`COMMENT ON COLUMN "cities"."name" IS 'название города'`);
        await queryRunner.query(`COMMENT ON COLUMN "cities"."id" IS 'уникальный идентификатор'`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."longitude" IS 'долгота'`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."latitude" IS 'широта'`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."city_id" IS 'ссылка на город'`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."type" IS 'тип здания (Жилое, многоквартирное и т.д.)'`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."big_folk_district_id" IS 'ссылка на большой народный район'`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."folk_district_id" IS 'ссылка на народный район'`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."is_fake" IS 'признак фейкового здания (0 - реальное, 1 - фейковое)'`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."district_id" IS 'ссылка на официальный район'`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."number" IS 'номер дома'`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."street_id" IS 'ссылка на улицу'`);
        await queryRunner.query(`COMMENT ON COLUMN "buildings"."id" IS 'уникальный идентификатор'`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts_buildings"."building_id" IS 'ссылка на здание'`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts_buildings"."blackout_id" IS 'ссылка на отключение'`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts_buildings"."id" IS 'уникальный идентификатор'`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."source" IS 'источник информации '`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."type" IS 'тип отключения'`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."description" IS 'описание отключения'`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."predicted_end_date" IS 'предсказанное время окончания отключения'`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."end_date" IS 'время окончания отключения'`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."start_date" IS 'время начала отключения'`);
        await queryRunner.query(`COMMENT ON COLUMN "blackouts"."id" IS 'уникальный идентификатор '`);
        await queryRunner.query(`COMMENT ON COLUMN "big_folk_districts"."name" IS 'название района'`);
        await queryRunner.query(`COMMENT ON COLUMN "big_folk_districts"."id" IS 'уникальный идентификатор'`);
        await queryRunner.query(`COMMENT ON COLUMN "folk_districts"."name" IS 'название района'`);
        await queryRunner.query(`COMMENT ON COLUMN "folk_districts"."id" IS 'уникальный идентификатор'`);
        await queryRunner.query(`COMMENT ON COLUMN "districts"."name" IS 'название района'`);
        await queryRunner.query(`COMMENT ON COLUMN "districts"."id" IS 'уникальный идентификатор'`);
        await queryRunner.query(`DROP TABLE "complaints"`);
        await queryRunner.query(`COMMENT ON TABLE "streets" IS 'справочник улиц'`);
        await queryRunner.query(`COMMENT ON TABLE "cities" IS 'справочник городов'`);
        await queryRunner.query(`COMMENT ON TABLE "buildings" IS 'справочник зданий'`);
        await queryRunner.query(`COMMENT ON TABLE "blackouts_buildings" IS 'связь отключений со зданиями (многие-ко-многим)'`);
        await queryRunner.query(`COMMENT ON TABLE "blackouts" IS 'таблица отключений систем ЖКХ (официально, источник - неизвестный)'`);
        await queryRunner.query(`COMMENT ON TABLE "big_folk_districts" IS 'справочник крупных народных районов'`);
        await queryRunner.query(`COMMENT ON TABLE "folk_districts" IS 'справочник народных/неформальных районов'`);
        await queryRunner.query(`COMMENT ON TABLE "districts" IS 'справочник официальных административных районов'`);
        await queryRunner.query(`ALTER TABLE "streets" ADD CONSTRAINT "streets_city_id_fkey2" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "streets" ADD CONSTRAINT "streets_city_id_fkey1" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "streets" ADD CONSTRAINT "streets_city_id_fkey" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "buildings_street_id_fkey" FOREIGN KEY ("street_id") REFERENCES "streets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "buildings_folk_district_id_fkey" FOREIGN KEY ("folk_district_id") REFERENCES "folk_districts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "buildings_district_id_fkey" FOREIGN KEY ("district_id") REFERENCES "districts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "buildings_city_id_fkey" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "buildings_big_folk_district_id_fkey" FOREIGN KEY ("big_folk_district_id") REFERENCES "big_folk_districts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" ADD CONSTRAINT "blackouts_buildings_building_id_fkey" FOREIGN KEY ("building_id") REFERENCES "buildings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" ADD CONSTRAINT "blackouts_buildings_blackout_id_fkey4" FOREIGN KEY ("blackout_id") REFERENCES "blackouts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" ADD CONSTRAINT "blackouts_buildings_blackout_id_fkey3" FOREIGN KEY ("blackout_id") REFERENCES "blackouts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" ADD CONSTRAINT "blackouts_buildings_blackout_id_fkey2" FOREIGN KEY ("blackout_id") REFERENCES "blackouts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" ADD CONSTRAINT "blackouts_buildings_blackout_id_fkey1" FOREIGN KEY ("blackout_id") REFERENCES "blackouts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blackouts_buildings" ADD CONSTRAINT "blackouts_buildings_blackout_id_fkey" FOREIGN KEY ("blackout_id") REFERENCES "blackouts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blackouts" ADD CONSTRAINT "fk_blackouts_initiators" FOREIGN KEY ("initiator_id") REFERENCES "initiators"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
